config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/signup', to: 'users#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/postonce', to: 'postonces#create'
  delete "/postonce#{/\d+/}", to: 'postonces#destroy'
 
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  resources :users do 
  	member do 
  		get :following, :followers 
  	end
  end
  resources :products, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :postonces, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		@feed_items = current_user.feed.all
  		@feed_news = current_user.feed.all
  	end
  	
  	@postonces = Postonce.all
  	@postonce = Postonce.new
  	@microposts = Micropost.all
    @micropost = Micropost.new
    
    @comment = Comment.new
  end
  def help
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<div class="help">
    <h2> Hướng dẫn sử dụng </h2>
    <p> Kính chào bà con, </p>
    <p>Cổng thông tin Chợ Đầm là nơi bà con có thể bán buồng chuối vừa chín cây trong vườn, hoặc mua ít trứng gà mới đẻ nhà các bà con khác. Ngoài mục buôn bán trong làng, bà con còn thể đăng tản văn, tin đài cảnh giác hoặc đăng tranh bà con tự vẽ ảnh bà con tự chụp để giao lưu với tinh thần chia sẻ sự sáng tạo vô hạn.</p>
    <p>Hướng dẫn này sẽ giúp bà con làm quen với Chợ Đầm. Trang chính có 4 phần:</p>
    <ul>
	<li><b>Phần 1: Đầu trang.</b> Phần này có các đường dẫn giúp bà con đi từ quán của mình ra chợ hoặc ngược lại, hoặc xem danh sách tất cả bà con khác. Khi bà con chưa có và chưa vào tài khoản, thì chỉ có  đường dẫn đến bài hướng dẫn này thôi.</li>
	<li><b>Phần 2: Chào mời.</b> Phần này có tin hội làng, bà con chú ý đi xem. Ngoài ra có đăng bán nhanh không cần tài khoản và chỗ để đăng nhập vào chợ.</li>
	<li><b>Phần 3: Tôm tươi.</b> Phần này chính là phần trưng bày các sản phẩm của các bà con ta đăng lên. Bà con muốn ăn hàng mời ghé qua xem mỗi sáng.</li>
	<li><b>Phần 4: Bà con tích cực.</b> Phần này đăng hình tuyên dương các bà con tích cực. </li>
	<li><b>Phần 5: Bảng tin.</b> Phần này là phần bà con có thể đăng tản văn tự viết, tranh tự vẽ, ảnh tự chụp để giao lưu với tinh thần chia sẻ học hỏi.</li>
    </ul>
    <h2> Phần một: Đầu trang </h2>
    <%= image_tag('dautrang.png')%>
    <ul>
	<li>Bà con nhấn vào chữ Chợ Đầm để ra chợ. Chính là trang chính. </li>
	<li>Bà con nhấn vào Hướng dẫn để ra bài hướng dẫn này. </li> 
    </ul>
    <p> Khi nào bà con đăng nhập vào quán của bà con thì phần đầu trang sẽ có nhiều đường dẫn hơn. Giờ tạm thế. </p>
    <%= image_tag('dangnhap4.png')%>
    <h2> Phần hai: Chào mừng. </h2>
    <p>Bà con có thể thấy ngay phần chào mừng có 3 hộp nhỏ:</p>
    <%= image_tag('chaomung.png')%>
    <ul>	
	<li> Hộp thứ nhất nói rằng nếu bà con muốn ăn hàng thì kéo xuống dưới (vào chợ) để xem nhà ai đang bán gì ta ăn. Ví dụ lâu ngày thèm ăn bún cá. Trong hộp này cũng có lịch hội làng. Bà con chú ý đi xem.</li>
	<%= image_tag('chaomung2.png', class: 'small')%>
	<li>Hộp thứ hai là hộp đăng bài nhanh.</li>
	    <%= image_tag('dangnhanh.png', class: 'small')%>
    </ul>
    <p>    Thế nào là đăng bài nhanh? Ví dụ sáng ra bà con phát hiện gà vừa nhảy ổ, muốn đăng bán luôn chục trứng, nhưng lại đang vội đi ra đồng rừng rẫy cỏ. Bà con có thể chụp hình, viết giá, viết số điện thoại liên lạc đăng lên luôn. Sau đó tất tả đi làm. Khi có người gọi đến, bà con bắt thằng cu tèo chạy bộ đi free ship (miễn phí giao hàng) cho người ta. Chạy bộ từ thôn Hộ Tứ ra đầu cầu Tân Lập chả hạn. Đấy là nói thí dụ thế. Cách đăng bài nhanh như sau:</p>
    <ul>
	<li> Bước một: Điền thông tin (tên, số điện thoại, sản phẩm, giá tiền).</li>
	<%= image_tag('dangnhanh2.png', class:'small')%>
	<li>   Bước hai: Nhấn nút để chọn hình ảnh đính kèm vào để đăng lên.
	</li>  <%= image_tag('dangnhanh3.png')%>
	<li> Bước ba: Ấn đăng sản phẩm.
	</li> <%= image_tag('dangnhanh4.png', class:'small')%>
    </ul>
    <p>Nếu thất bại, bà con sẽ thấy thông báo màu đỏ nói rằng chưa đăng được, bà con nên kiểm tra lại. Hoặc là quên viết thông tin (ai biết mà gọi), hoặc là thông tin quá dài (quá 140 chữ cái).</p>
	    <%= image_tag('dangnhanh0.png')%>
    <p>   Nếu thành công, bà con sẽ thấy thông báo màu xanh. Khi đó món hàng của bà con đã được ra chợ. Tức là tin bán đã được cho vào phần Tôm tươi ở bên dưới, mời bà con kéo xuống để vào chợ xem.</p>
	<%= image_tag('dangnhanh5.png')%>
    <h2> Phần ba: Tôm tươi </h2>
    <p>Khi kéo xuống (vào chợ), ở mục Tôm tươi, bà con sẽ thấy món hàng của mình đứng cạnh các món hàng khác. Giờ yên tâm đi rẫy cỏ, nhỉ.</p>
    <%= image_tag('dangnhanh6.png')%>

    <li>Hộp thứ ba ờ phần hai Chào mừng, là hộp dành cho bà con nào đã có tài khoản, hoặc chưa có nhưng muốn đăng ký để bán lâu dài cho dễ.</li>
    
    <%= image_tag('dangky.png', class:'small')%> <br>
    Trường hợp một: Muốn đăng ký tài khoản: 
    <ul><li>Bước một: Nhấn vào chữ Đăng ký màu xanh. Đợi trang Đăng ký hiện ra.
    </li><%= image_tag('dangky2.png', class: 'small')%>
    <li>    Bước hai: Điền tên.</li>
    <li>    Bước ba: Điền email dễ nhớ. </li>
    <li>Bước ba: Điền mật khẩu dễ nhớ.</li>
    <li>Bước bốn: Nhập lại mật khẩu.</li>
    <li>Bước năm: Nhấn Đăng ký.</li>
    <%= image_tag('dangky4.png')%>
    </ul>
    </p>
    <p>
	Nếu thất bại, sẽ hiện ra thông báo đỏ nói đơn của bà con có bao nhiêu lỗi.<br>
	<%= image_tag('dangky3.png', class: 'small')%><br>
	
	Nếu thành công, sẽ hiện ra thông báo xanh chào mừng bà con.</p>
	<%= image_tag('dangky5.png')%>

    Đây chính là quán của bà con để buôn bán lâu dài. Tạm thời bây giờ ta ấn vào Thoát, bà con sẽ ra thoát ra khỏi trang đó để về lại trang chủ. Từ đây ta lại đăng nhập lại.
    <%= image_tag('dangnhap.png', class: 'small')%>
    <ul>
	<li>    Bước một: Điền email </li>
	<li>Bước hai: Điền mật khẩu <br>
	Nếu bà con dùng điện thoại hay máy tính riêng thì có thể chọn Ghi nhớ tôi để lần sau đỡ đăng nhập lại. </li>
	<li>Bước ba: Nhấn đăng nhập.</li>
    </ul>

<p>
    Sau khi đăng nhập thành công, quán của bà con sẽ hiện ra.<br>
    <%= image_tag('dangnhap2.png')%><br>
    Quán của bà con có ba hộp, hộp thứ nhất nói về thông tin của bà con, xem hiện đang bán bao nhiêu sản phẩm, đã viết bao nhiêu tản văn, hay có bao nhiêu người đợi tin và đang đợi tin bao nhiêu người. Hộp thứ ba là sửa thông tin cá nhân và đăng ảnh đại diện. Hộp thứ hai là để đăng sản phẩm:
    <%= image_tag('dangnhap3.png', class: 'small')%><br>
    Nếu bà con đăng sản phẩm ở đây, sản phẩm tự hiện ra trong quán (tí kéo xuống là thấy), và tự hiện ra cả ở trang chính Chợ Đầm (phần Tôm tươi ạ). Ví dụ, bà con đăng xong, rồi chạy ra chợ bằng cách ấn vào chữ Chợ Đầm ở phần đầu trang.
    <%= image_tag('dangnhap4.png')%>
    Sau khi ra chợ rồi, bà con kéo xuống sẽ thấy bài viết vừa đăng hiện sẵn ở mục Tôm tươi. Hê hê.
    <%= image_tag('dangnhap5.png')%>
</p>
<p>
    Bà con ấn vào chữ Quán của tôi ở phần đầu trang để về lại quán mình. Vẫn ở hộp thứ hai, ngoài việc đăng bán chuối, bà con có thể viết chút tản văn lơ đãng như hồn mây mơ trời chiều lồng lộng gió. Ví dụ:<br>
    <%= image_tag('dangnhap6.png', class: 'small')%><br>

    Bà con có thể chọn thêm hình hoặc không cần thiết. Nhiều khi văn ngắn là văn dài và ngược lại. Bà con có thể thắc mắc tại sao trong nội dung của tản văn lại có nhiều dấu sao thế kia? Bà con chịu khó làm theo tí tôi bẩu. Sau khi đăng lên thành công, bà con kéo xuống dưới để xem tản văn.
    <%= image_tag('dangnhap8.png')%>

    Bà con có thể thấy rằng, những chữ nào được bọc dấu sao ở quanh sẽ có sự khác biệt. Văn bản này được đánh phấn hoa lá cành in nghiêng in đậm cả. Làm sao để biết được điều này? <br>
    <%= image_tag('dangnhap7.png', class: 'small')%><br>
    Thật tiện là nhân vật Cô Dậu đã viết một tản văn để hướng dẫn mọi người cách viết tản văn có in đậm, in nghiêng cho đẹp mắt và thể hiện được cá tính của tản văn: ví dụ chỗ nào sôi nổi như sóng trào chỗ nào thì thầm im lặng như tiếng hoa bay.<br>

    <%= image_tag('dangnhap9.png', class: 'small')%><br>

        Đang ở cuối trang Quán của tôi, bà con nhấn vào nút Lên đầu để về đầu trang, sau đó ấn chữ Chợ Đầm ở phần đầu trang để ra chợ xem tản văn của mình đã được đăng lên phần Bảng tin xem nó như thế nào.
    </p> 
    <h2> Phần năm Bảng tin</h2>
    Sau khi về trang chính Chợ Đầm bà con kéo xuống dưới tìm mục Bảng tin Bà con chú ý. Khi đó sẽ thấy bài viết của mình hiện ra cùng với những người khác.
    <%= image_tag('bangtin.png')%><br>
    Sau khi xem xét bảng tin, bà con nhận ra rằng, cũng có những bà con khác nữa nhưng họ đăng tranh họ vẽ, có người thì đăng ảnh họ chụp. Tức là ngoài việc đăng tản văn, bà con không cần viết nội dung mà chỉ chọn hình để đăng tranh mình vẽ, hình mình chụp cũng được. Đều là các tác phẩm nghệ thuật cả.
    <%= image_tag('bangtin2.png')%>
</p>
<p>
    Nhìn lại vào thanh màu đỏ đầu trang, ta đi tiếp đến mục Tất cả bà con.
    <%= image_tag('dangnhap4.png')%>
    Ở trang này hiện ra tất cả bà con mà có đăng ký quán ở Chợ Đầm cùng với thông tin họ đang bán bao nhiêu sản phẩm, đã có bao nhiêu tác phẩm nghệ thuật và đang đợi tin ai hay có ai đợi tin.
    <%= image_tag('tatca.png')%>

    Ví dụ nếu bà con chọn đợi tin của Bà Quế, khi nào Bà Quế đăng sản phẩm hoặc đăng tản văn, những thứ đó sẽ hiện ra ở trang Chợ Đầm của chính bà con.
    Ví dụ bà con đợi tin Anh Chí, Anh Chí có rất nhiều tác phẩm do anh tự vẽ.
    <%= image_tag('anhchi.png')%><br>

    Hoặc bà con có thể đợi tin Hào Hai, Hào Hai viết rất nhiều tin tức cảnh giác bổ ích cho bà con.
    <%= image_tag('haohai.png')%><br>

    Cô Dậu chính là người viết tản văn hướng dẫn tạo văn bản đẹp cho bà con đọc ở Bảng tin. Cô viết về khoa học công nghệ thường xuyên. Vì vậy bà con có thể theo dõi để lấy thông tin bổ ích.
    <%= image_tag('codau.png')%><br>

    Cu Tèo ngoài nhận chạy bộ giao hàng, còn học và tạo hình động về thí nghiệm lưỡng tính sóng hạt của electron, giảng giải về lượng tử. Nếu bà con quan tâm, có thể đợi tin Cu Tèo.
    <%= image_tag('cuteo.png')%><br>
    
    Ngoài ra bà con cũng thấy rằng dưới mỗi tản văn đều có bình luận. Bà con tham gia bình luận sôi nổi mọi người mừng.<br>
    <%= image_tag('binhluan.png', class: 'small') %><br>

    Lưu ý bà con cần đăng nhập mới thấy được khung bình luận. Sau khi gõ vào khung ý kiến mình thấy có thể đóng góp thêm, bà con nhấn nút Đăng và sẽ thấy bình luận hiện ra ở dưới tản văn.<br>
    <%= image_tag('binhluan2.png', class: 'small')%><br>
    <%= image_tag('binhluan3.png', class: 'small')%><br>

    Những bà con tích cực (đăng sản phẩm và đăng tản văn sẽ được tuyên dương ở phần bốn Bà con Tích cực ở trang chủ Chợ Đầm.
</p>
    <h2> Phần bốn: Bà con Tích cực </h2>
    Phần này đăng hình tuyên dương những bà con có nhiều đóng góp nhất cho thôn bản.

    <%= image_tag('tichcuc.png')%><br>

    <p>Khi bà con đăng nhiều sản phẩm sáng tạo, sẽ có nhiều người đợi tin của chính bà con. <b>Chúc bà con vui khỏe!</b></p>
	</div>

app/views/static_pages/home.html.erb
   
<% if !logged_in? %>

<section class="banner">
    <div class="notice">
        <p> Bà con sáng ra muốn ăn hàng? Mời vào chợ xem hàng xôi nhà bác May và bún cá nhà bác Hoa.</p>
        <p> Lịch hội làng: </p>
        <ul>
            <li> Cắm trại: 30/6. </li>
            <li>Đua thuyền: Ra giêng</li>
        </ul>
    </div>
    <div class="once">
        <p>Mụ gà nhảy ổ nhà bà con mới đẻ chục trứng? Mời bà con đăng bán luôn: </p>
        <%= form_for(:postonce, :url => {:controller=>"postonces",:action=>"create"}) do |f| %>
        <%= f.text_area :content, placeholder: "Tên bà con, giá tiền, điện thoại để người ta gọi.." %>
        <%= f.label :picture, "Hình sản phẩm" %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'file'  %>
        <%= f.submit "Đăng sản phẩm", class: 'btn btn-primary' %>
        <% end %>
    </div>
    <div class="login">
      <div class="row">
        <div class="col-md-12">
            <p> Nếu bà con tính đăng bán lâu dài, mời 
                <%= link_to "Đăng ký", signup_path %>. </p>
                <p> Nếu bà con đã có tài khoản, mời đăng nhập:</p>
                <%= form_for(:session, :url=>{:controller=>"sessions",:action=>"create"}) do |f| %>
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
                <%= f.label :password, "Mật khẩu" %> 
                <%= f.password_field :password, class: 'form-control' %>
                <%= f.label :remember_me, class: "checkbox inline" do %>
                <%= f.check_box :remember_me %>
                <span>Ghi nhớ tôi</span>
                <% end %>
                <%= f.submit "Đăng nhập", class: 'btn btn-primary' %>
                <% end %>
            </div>
        </div>
    </div>
</section>
<% end %>
<section class="hot-products">
    <h2> Tôm tươi  </h2>
    <div class="homefeed">
        <% if !logged_in? %>
        <% user = User.find_by(admin: true) %>
        <% @feed_items = (user ? user.feed : []) + Postonce.all %>
        <% else %>
        <% @feed_items = current_user.feed + Postonce.all %>
        <% end %>
        
        <%= render 'shared/feed' %>
    </div>
</section>
<section class="hot-users">
    <h2> Bà con tích cực </h2>
    <% @hots = User.all.sort_by { |u| -u.products.count } %>
    <% @tops = @hots.length >= 4 ? @hots[0..3] : @hots %>    
    <div class="users">
      <% @tops.each do |user| %>
      <section>
          <div class="ava">            
              <% if user.picture? %>
              <%= image_tag user.picture.url %>
              <% else %>
              <%= image_tag('wolf.jpg', alt: 'wolf') %>
              <% end %> 
          </div>
          <p><%= link_to user.name, user %>
           <% @user = user %>



            <%= render 'shared/stats' %>
            đang bán <%= @user.products.count %>    sản phẩm <br> 
            và có <%= @user.microposts.count %> tản văn.

<% if logged_in? %>

            <% unless current_user?(@user) %>
<% if current_user.following?(@user) %>
<%= render "users/unfollow" %>
<% else %>
<%= render "users/follow" %>
<% end %>
<% end %>
   <% end %>
        </p>


    </section>
    <% end %>
</div>
</section>

<section class="hot-news">
    <h2> Bà con chú ý </h2>
    <% if !logged_in? %>
    <% user = User.find_by(admin: true) %>
    <% @feed_news = user ? user.feednews : [] %>
    <% else %>
    <% @feed_news = current_user.feednews %>
    <% end %>
    <div class="news">
    <%= render 'shared/feed_news' %>
</div>
</section>