config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/signup', to: 'users#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/postonce', to: 'postonces#create'
  delete "/postonce#{/\d+/}", to: 'postonces#destroy'
 
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  resources :users do 
  	member do 
  		get :following, :followers 
  	end
  end
  resources :products, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :postonces, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment, :url => {:controller=>"comments",:action=>"create"}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :micropost_id, @micropost_id %>

  
    <%= f.text_area :content, placeholder: "Sao?" %>
  <%= f.submit "Đăng", class: "btn btn-primary" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    Đơn bạn vừa nhập có <%= object.errors.count %> lỗi. Vui lòng kiểm tra.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<%= render @feed_items %>
<% end %>

app/views/shared/_feed_news.html.erb
<% if @feed_news.any? %>
<%= render @feed_news %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :header, "Tiêu đề:" %>
      <%= f.text_field :header, class: 'form-control' %>
<div>

	<%= f.label :content, "Nội dung:" %><br>
  <%= f.text_area :content, placeholder: "Heminway trong 500 chữ cái..", size: '23x10' %>

</div> 
<%= f.label :name, "Thêm hình:" %>
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'file'  %>
<%= f.submit "Đăng tản văn", class: 'btn btn-primary' %>
<% end %>

app/views/shared/_product_form.html.erb
<%= form_for(@product) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div>
  <%= f.text_area :content, placeholder: "Giá tiền, điện thoại liên hệ.." %>
</div> 
<%= f.label :name, "Thêm hình:" %>
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'file'  %>
<%= f.submit "Đăng sản phẩm", class: 'btn btn-primary' %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<p><a href="<%= following_user_path(@user) %>">
  đang đợi tin <%= @user.following.count %> người
  
</a><br>
<a href="<%= followers_user_path(@user) %>">
  có <%= @user.followers.count %>
  người đợi tin
</a>
</p> 