config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/signup', to: 'users#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/postonce', to: 'postonces#create'
  delete "/postonce#{/\d+/}", to: 'postonces#destroy'
 
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  resources :users do 
  	member do 
  		get :following, :followers 
  	end
  end
  resources :products, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :postonces, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Chợ Đầm", root_path %>

  </header>

app/views/layouts/_navigation.html.erb
<nav>

<% if logged_in? %>
	<%= link_to "Tất cả bà con", users_path %>
	<%= link_to "Quán của tôi", current_user %>
	<%= link_to "Thoát", logout_path, method: :delete %>
<% end %>

<%= link_to "Hướng dẫn", help_path %>



</nav>

app/views/layouts/_totopbutton.html.erb
<button id="toTop"
    title="Go to Top" style="font-weight:bold"> lên đầu &#8593;</button>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-31832445-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-31832445-3');
</script>

<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("9nS5mpkJ4LivI7iiIWJLJLQ3YVoJyC9c");
  analytics.page();
  }}();
</script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
  	<%= render 'layouts/navigation' %>
 

	
	<main>
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
</main>
    <%= render 'layouts/totopbutton' %>
<%= debug(params) if Rails.env.development? %>
  </body>
</html>